### ISSUE TITLE
Download into the shared drive rather than my drive

### ISSUE THREAD

**Issue by phreakcoder** [r12habh/Google-Colab-Torrent-Downloader-To-Drive#14]
i have a shared drive with lots of space than my default google drive. so is there any way i can download directly into the shared drive rather than my drive. i tried changing the savepath in add torrent file code but throws an error.

**Comment by priyaranjankumar** [comment]
You can do this by changing the value of  `save_path` variable
```py
    'save_path': '/content/drive/My Drive/Torrent/'
```
to 
```py
     'save_path': '/content/drive/Shared drives/test/Torrent/'
     or
     'save_path': '/content/drive/Shared drives/<shared-drive-name>/Torrent/'
```


Notice: here `test` is name of my shared drive, so change it accordingly to yours.

**Comment by nutcyy87** [comment]
> You can do this by changing the value of `save_path` variable
> 
> ```python
>     'save_path': '/content/drive/My Drive/Torrent/'
> ```
> 
> to
> 
> ```python
>      'save_path': '/content/drive/Shared drives/test/Torrent/'
>      or
>      'save_path': '/content/drive/Shared drives/<shared-drive-name>/Torrent/'
> ```
> 
> Notice: here `test` is name of my shared drive, so change it accordingly to yours.

hi brother
when i download torrent file,it save as a folder
and if i want dowload folder,google drive zips folder and i can download it as zip file but it take more time
is any way that i download torrent file as zip file to drive directly?

**Comment by ethanaobrien** [comment]
@nutcyy87 Version 4 adds support for save as zip file. 

@r12habh Please close this. I do not see a need to keep it opened
